#+TITLE: Emacs Config
#+AUTHOR: Daniel Mircea

[[https://img.shields.io/badge/Linux-yes-brightgreen.svg?style=flat]]
[[https://img.shields.io/badge/Mac-yes-brightgreen.svg?style=flat]]

This is my personal emacs configuration.

** Dependencies
| =chruby=       | Ruby version manager |
| =ripgrep=      | Rust based grep      |

** Installation
#+BEGIN_SRC sh
  git clone git@github.com:viseztrance/.emacs.d.git ~/.emacs.d
#+END_SRC

** Configuration

*** Keys
In order to memorize less commands, running certain key combinations again, changes their behaviour.

| F6          | Version control (magit)           |
| F2          | Rename variable or method (eglot) |
| F2 F2       | Rename opened file                |
| C-.         | Find file in project              |
| C-. C-.     | Search for text in project        |
| C-M-%       | Regexp query replace              |
| C-M-% C-M-% | Regexp query replace in project   |
| C-c w       | Toggle whitespace visibility      |

*** HIDPI Scaling
The theme customizations uses different font sizes. Adjusting them to different dpis is tricky.
You can change ALL the font sizes by using the following in =~/.emacs.d/custom.el=

#+BEGIN_SRC elisp
  (setq me/font-scaling-ratio 1.5)
#+END_SRC

This example makes every font 50% larger.

*** Ruby

=chruby= will try to use the project's ruby version from the =.ruby-version= file in the projects root.
If no such file exists it will fallback to the latest ruby available on the system to =chruby=.

A specific version can also be provided as follows:

#+BEGIN_SRC elisp
  (setq me/ruby-preffered-version "3.1.3")
#+END_SRC
